### ISSUE TITLE
no file found error

### ISSUE THREAD

**Issue by ashwinsingh2007** [longbill/node-phpfpm#1]
I have my php-fpm server running on 127.0.0.1:9000,
## and i run the file node server.js where server.js contains:-

var PHPFPM = require('node-phpfpm');

var phpfpm = new PHPFPM(
{
host: '127.0.0.1',
port: 9000,
documentRoot: __dirname+'/'
});

phpfpm.run('test.php', function(err, output, phpErrors)
{
if (err == 99) console.error('PHPFPM server error');
//console.log(output);
if (phpErrors) console.error(phpErrors);
## });

but i got an error:-
unable to open primary script : /root/Desktop/programs/php/php/test.php (No such file or directory).

**Comment by longbill** [comment]
/root/Desktop/programs/php/php/test.php

Does this file exist?
Ashwin Singh notifications@github.com于2016年3月14日 周一18:17写道：

**Comment by ashwinsingh2007** [comment]
Yes

**Comment by longbill** [comment]
Just rechecked this issue.  Your code works perfectly on my Mac and linux server.

my php-fpm server version is:

``` bash
➜ node-phpfpm php-fpm -v
PHP 5.6.19 (fpm-fcgi) (built: Mar 17 2016 00:37:42)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
