### ISSUE TITLE
有没有express结合的DEMO呢？

### ISSUE THREAD

**Issue by lidenggao** [longbill/node-phpfpm#3]
我用第三方的包里面自带的express服务，想把请求转由php处理，用到了你的这个模块，你做得非常棒，但我对于express的post数据处理不太了解，不知道如何将express收到的数据全数交给node-phpfpm，能不能给提供个node-phpfpm结合express的中间件或文档？

**Comment by longbill** [comment]
没有。 不过你可以自己做。 express的post数据，需要你自己通过 req.on('data') 来获取。或者通过某个中间件帮你干这个事情。
拿到post数据，然后再发送给php。

**Comment by lidenggao** [comment]
嗯，只能如此了，谢谢
