### ISSUE TITLE
is not asynchronous

### ISSUE THREAD

**Issue by pixelpaulaus** [longbill/node-phpfpm#7]
this does not seem to be asynchronous.

`await php.run()`

simply does not work in a asynchronous manner

**Comment by longbill** [comment]
php.run() does not return a promise.   you have to use callback.  

because it will return 3 parameters to the callback function which can not be transformed to promise states.

**Comment by pixelpaulaus** [comment]
i thought about that after i posted sorry.

but now i have a strange issue where if a throw new exception within the callback node crashes, and it seems to be only with your module.

**Comment by longbill** [comment]
any uncaught exception will crash the node process.  you can wrap the callback into a promise, and use reject instead of throw.
